# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d85936fa8964bbb8971db959606ac733c7d8997f5ac4807fae81fa7939ea99b499fb772a5eb37ed0e2c85d19e80f98ae7bb5fd2d12a7b9ca015ddc5db8ecfd59

test:
  secret_key_base: 3466117672912831baf6bf010a8921417d493070cce22ffb390b3705889293d1793f8f5f404294902c04c3e8fc1679686b86048f2341393b40344114d3d51c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
